spring:
  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: userdata
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: tu-secreto-super-seguro-cambiar-en-produccion
  expiration: 86400000 # 24 horas